/**
 * Task data model definitions.
 * Tasks are dynamically generated by the NPC Agent, but follow a strict schema.
 */

const VALID_CONDITION_TYPES = ['kill_monster', 'collect_item', 'talk_to_npc', 'use_item'];
const VALID_AWARD_TYPES = ['gold', 'exp', 'item'];
const VALID_STATUSES = ['pending', 'in_progress', 'completed'];

/**
 * Create a task data template.
 * @param {object} params
 * @param {string} params.task_id
 * @param {string} params.player_id
 * @param {string} params.npc_id
 * @param {string} params.title
 * @param {string} params.description
 * @param {Array} params.conditions - [{type, target_id, required_count, current_count}]
 * @param {Array} params.awards - [{type, value?, item_id?, quantity?}]
 * @returns {object}
 */
function createTaskData({
  task_id,
  player_id,
  npc_id,
  title,
  description,
  conditions,
  awards,
}) {
  const now = new Date().toISOString();
  return {
    task_id,
    player_id,
    npc_id,
    title,
    description,
    status: 'pending',
    conditions: conditions.map((c) => ({
      type: c.type,
      target_id: c.target_id,
      required_count: c.required_count || 1,
      current_count: c.current_count || 0,
    })),
    awards: awards.map((a) => ({
      type: a.type,
      value: a.value || null,
      item_id: a.item_id || null,
      quantity: a.quantity || null,
    })),
    created_at: now,
    completed_at: null,
  };
}

module.exports = {
  VALID_CONDITION_TYPES,
  VALID_AWARD_TYPES,
  VALID_STATUSES,
  createTaskData,
};
